"""
collaborative_filtering.py

This module contains the core logic for the item-based collaborative filtering
recommendation engine. It uses a sparse user-item interaction matrix to compute
item-item similarities and generate personalized recommendations for users.

The main class, `CollaborativeFilteringRecommender`, provides methods to:
- Fit the model on historical interaction data.
- Predict a list of recommended items for a given user.
- Save and load the trained model for persistence.
"""

import logging
import time
from typing import List, Dict, Any

import joblib
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.metrics.pairwise import cosine_similarity

# Configure logger for the module
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


class CollaborativeFilteringRecommender:
    """
    An item-based collaborative filtering recommender system.

    This class builds a recommendation model based on user-item interactions.
    It calculates the cosine similarity between items to find items that are
    "similar" based on user interaction patterns. Recommendations for a user
    are then generated by finding items similar to the ones they have already
    interacted with positively.

    Attributes:
        item_similarity_matrix (np.ndarray): A square matrix where each element [i, j]
                                             is the cosine similarity between item i and item j.
        user_item_matrix (csr_matrix): A sparse matrix of user-item interactions.
        user_map (Dict[Any, int]): A mapping from original user IDs to internal matrix indices.
        item_map (Dict[Any, int]): A mapping from original item IDs to internal matrix indices.
        inverse_item_map (Dict[int, Any]): A mapping from internal matrix indices back to original item IDs.
    """

    def __init__(self):
        """Initializes the recommender model components to None."""
        self.item_similarity_matrix: np.ndarray | None = None
        self.user_item_matrix: csr_matrix | None = None
        self.user_map: Dict[Any, int] | None = None
        self.item_map: Dict[Any, int] | None = None
        self.inverse_item_map: Dict[int, Any] | None = None
        logger.info("CollaborativeFilteringRecommender initialized.")

    def fit(self, interactions_df: pd.DataFrame):
        """
        Trains the recommender model on the provided interaction data.

        This method performs the following steps:
        1. Creates a sparse user-item interaction matrix.
        2. Computes the item-item cosine similarity matrix.
        3. Stores the matrices and ID mappings for prediction.

        Args:
            interactions_df (pd.DataFrame): A DataFrame with at least three columns:
                                            'user_id', 'item_id', and 'rating'.
                                            'rating' should be a numerical value
                                            representing the user's interaction
                                            (e.g., 1 for a view, 5 for a purchase).
        """
        if not all(col in interactions_df.columns for col in ['user_id', 'item_id', 'rating']):
            raise ValueError("Input DataFrame must contain 'user_id', 'item_id', and 'rating' columns.")

        logger.info(f"Starting model fitting with {len(interactions_df)} interactions.")
        start_time = time.time()

        self._create_utility_matrix(interactions_df)
        self._calculate_item_similarity()

        end_time = time.time()
        logger.info(f"Model fitting completed in {end_time - start_time:.2f} seconds.")

    def _create_utility_matrix(self, interactions_df: pd.DataFrame):
        """
        Creates the user-item utility matrix and corresponding ID maps.

        Args:
            interactions_df (pd.DataFrame): The interaction data.
        """
        logger.info("Creating user-item utility matrix...")

        # Create mappings from original IDs to matrix indices
        self.user_map = {user_id: i for i, user_id in enumerate(interactions_df['user_id'].unique())}
        self.item_map = {item_id: i for i, item_id in enumerate(interactions_df['item_id'].unique())}
        self.inverse_item_map = {i: item_id for item_id, i in self.item_map.items()}

        # Map IDs in the DataFrame to indices
        user_indices = interactions_df['user_id'].map(self.user_map)
        item_indices = interactions_df['item_id'].map(self.item_map)
        ratings = interactions_df['rating']

        # Create the sparse matrix
        num_users = len(self.user_map)
        num_items = len(self.item_map)
        self.user_item_matrix = csr_matrix((ratings, (user_indices, item_indices)), shape=(num_users, num_items))
        logger.info(f"Utility matrix created with shape {self.user_item_matrix.shape} and "
                    f"{self.user_item_matrix.nnz} non-zero elements.")

    def _calculate_item_similarity(self):
        """
        Calculates the cosine similarity matrix for items.
        The similarity is calculated on the item-user matrix (transpose of user-item).
        """
        if self.user_item_matrix is None:
            raise RuntimeError("User-item matrix has not been created. Call fit() first.")

        logger.info("Calculating item-item cosine similarity matrix...")
        # We need to compute similarity between items, so we transpose the matrix
        # to have items as rows.
        item_user_matrix = self.user_item_matrix.T.tocsr()
        self.item_similarity_matrix = cosine_similarity(item_user_matrix, dense_output=True)
        # Set diagonal to 0 to avoid recommending an item itself
        np.fill_diagonal(self.item_similarity_matrix, 0)
        logger.info(f"Item similarity matrix calculated with shape {self.item_similarity_matrix.shape}.")

    def predict(self, user_id: Any, n_recommendations: int = 10) -> List[Any]:
        """
        Generates a list of recommended item IDs for a given user.

        Args:
            user_id (Any): The ID of the user to generate recommendations for.
            n_recommendations (int): The number of recommendations to return.

        Returns:
            List[Any]: A list of recommended item IDs, sorted by relevance.
                       Returns an empty list if the user is unknown or has no interactions.
        """
        if self.item_similarity_matrix is None or self.user_map is None or self.user_item_matrix is None:
            raise RuntimeError("Model is not fitted yet. Call fit() before making predictions.")

        if user_id not in self.user_map:
            logger.warning(f"User '{user_id}' not found in the training data. Cannot generate recommendations.")
            return []

        user_index = self.user_map[user_id]
        user_interactions = self.user_item_matrix.getrow(user_index)

        if user_interactions.nnz == 0:
            logger.warning(f"User '{user_id}' has no interactions in the training data.")
            return []

        # Calculate weighted scores for all items
        # This is the dot product of the user's interaction vector and the item similarity matrix
        scores = user_interactions.dot(self.item_similarity_matrix)

        # Exclude items the user has already interacted with
        interacted_item_indices = user_interactions.indices
        scores[interacted_item_indices] = -1  # Set to a low value to ensure they are not recommended

        # Get top N recommendations
        # `argpartition` is faster than `argsort` for finding top N
        top_indices = np.argpartition(scores, -n_recommendations)[-n_recommendations:]
        # Sort only the top N indices by score
        top_n_sorted_indices = top_indices[np.argsort(scores[top_indices])][::-1]

        # Map indices back to original item IDs
        recommendations = [self.inverse_item_map[i] for i in top_n_sorted_indices]

        logger.info(f"Generated {len(recommendations)} recommendations for user '{user_id}'.")
        return recommendations

    def save_model(self, file_path: str):
        """
        Saves the trained model components to a file using joblib.

        Args:
            file_path (str): The path to the file where the model will be saved.
        """
        model_data = {
            'item_similarity_matrix': self.item_similarity_matrix,
            'user_item_matrix': self.user_item_matrix,
            'user_map': self.user_map,
            'item_map': self.item_map,
            'inverse_item_map': self.inverse_item_map,
        }
        try:
            joblib.dump(model_data, file_path)
            logger.info(f"Model successfully saved to {file_path}")
        except Exception as e:
            logger.error(f"Error saving model to {file_path}: {e}")
            raise

    def load_model(self, file_path: str):
        """
        Loads a trained model from a file.

        Args:
            file_path (str): The path to the model file.
        """
        try:
            model_data = joblib.load(file_path)
            self.item_similarity_matrix = model_data['item_similarity_matrix']
            self.user_item_matrix = model_data['user_item_matrix']
            self.user_map = model_data['user_map']
            self.item_map = model_data['item_map']
            self.inverse_item_map = model_data['inverse_item_map']
            logger.info(f"Model successfully loaded from {file_path}")
        except FileNotFoundError:
            logger.error(f"Model file not found at {file_path}")
            raise
        except Exception as e:
            logger.error(f"Error loading model from {file_path}: {e}")
            raise


if __name__ == '__main__':
    # Example usage for demonstration and testing purposes
    logger.info("Running collaborative filtering example...")

    # 1. Create sample interaction data
    data = {
        'user_id': ['user1', 'user1', 'user2', 'user2', 'user3', 'user3', 'user3', 'user4', 'user4', 'user4'],
        'item_id': ['itemA', 'itemB', 'itemB', 'itemC', 'itemA', 'itemC', 'itemD', 'itemB', 'itemD', 'itemE'],
        'rating': [5, 4, 5, 3, 4, 5, 2, 4, 5, 3]
    }
    sample_df = pd.DataFrame(data)
    print("Sample Interaction Data:")
    print(sample_df)
    print("-" * 30)

    # 2. Initialize and fit the model
    recommender = CollaborativeFilteringRecommender()
    recommender.fit(sample_df)

    # 3. Get recommendations for a user
    target_user = 'user1'
    recommendations = recommender.predict(user_id=target_user, n_recommendations=2)
    print(f"Recommendations for {target_user}: {recommendations}")
    # Expected: user1 likes A and B. B is liked by user2 and user4. C is liked by user2. D is liked by user3 and user4.
    # So, items C and D should be good candidates.

    # 4. Test with a user with no interactions (in a larger dataset) or a new user
    new_user_recommendations = recommender.predict(user_id='user_new', n_recommendations=2)
    print(f"Recommendations for new_user: {new_user_recommendations}")
    print("-" * 30)

    # 5. Save and load the model
    model_path = 'cf_model.joblib'
    recommender.save_model(model_path)

    new_recommender = CollaborativeFilteringRecommender()
    new_recommender.load_model(model_path)

    # 6. Verify predictions from the loaded model
    loaded_model_recs = new_recommender.predict(user_id=target_user, n_recommendations=2)
    print(f"Recommendations for {target_user} from loaded model: {loaded_model_recs}")

    assert recommendations == loaded_model_recs
    print("\nExample run completed successfully.")